<?php

namespace Tests;

use App\Exceptions\Handler;
use App\User;
use Illuminate\Foundation\Testing\TestCase as BaseTestCase;
use Illuminate\Contracts\Debug\ExceptionHandler;
use function factory;

abstract class TestCase extends BaseTestCase
{

    use CreatesApplication;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        //$this->disableExceptionHandling();
    }

    public function signIn($user = null)
    {
        $user = $user ? : create(User::class);
        $this->actingAs($user);

        return $user;
    }

    public function signInAdmin()
    {
        $admin = factory('App\User')->state('administrator')->create();
        config(['icanmart.administrators'=>[$admin->email]]);

        return $this->signIn($admin);
    }


    //protected function disableExceptionHandling()
    //{
    //    $this->oldExceptionHandler = $this->app->make(ExceptionHandler::class);
    //
    //    $this->app->instance(ExceptionHandler::class, new class extends Handler
    //    {
    //
    //        public function __construct() {}
    //
    //        public function report(\Exception $e) {}
    //
    //        public function render($request, \Exception $e) { throw $e; }
    //
    //    });
    //}

    //protected function withExceptionHandling()
    //{
    //    $this->app->instance(ExceptionHandler::class, $this->oldExceptionHandler);
    //
    //    return $this;
    //}

}
