<?php

namespace Tests\Feature;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Notifications\DatabaseNotification;
use Symfony\Component\VarDumper\Cloner\Data;
use Tests\TestCase;

class BoxNotificaitonTest extends TestCase
{
    use RefreshDatabase;
    
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->signIn();
    }
    
    /** @test */
    public function user_can_fetch_their_unread_notifications()
    {
        create(DatabaseNotification::class);
    
        $user = auth()->user();
        $endpoint = "/profiles/{$user->name}/notifications/";
    
        $this->assertCount(1, $this->getJson($endpoint)->json());
        
    }
}
