<?php

namespace Tests\Feature;

use Tests\TestCase;
use Illuminate\Foundation\Testing\RefreshDatabase;

class BoxReadTest extends TestCase
{
    
    use RefreshDatabase;
    
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->box = create('App\Box');
    }
    
    
    /** @test */
    
    public function a_user_can_browse_all_boxes()
    {
        $response = $this->get('/boxes');
        
        $response->assertStatus(200);
    }
    
    /** @test */
    public function a_user_can_see_items_associated_with_box()
    {
        $this->signIn();
        
        $item = factory('App\Item')->create(['box_id' => $this->box->id]);
        //dd($item->product_name);
        $this->get($this->box->path())
             ->assertSee($item->product_name);
    }
    
}
