<?php

namespace Tests\Feature;

use Tests\TestCase;
use Illuminate\Foundation\Testing\RefreshDatabase;

class BoxReadTest extends TestCase
{

    use RefreshDatabase;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->box = create('App\Box');
    }


    /** @test */

    public function a_user_can_browse_all_boxes()
    {
        $this->signInAdmin();
        $response = $this->get('/boxes');

        $response->assertStatus(200);
    }

    /** @test */
    public function a_user_can_see_items_associated_with_box()
    {
        $this->signIn();

        $item = factory('App\Item')->create(['box_id' => $this->box->id]);
        //dd($item->product_name);
        $this->get($this->box->path())
             ->assertSee($item->product_name);
    }

    /** @test */
    //public function users_can_filter_boxes_by_any_seller_name()
    //{
    //    $seller = create('App\Seller',['name' => 'test','slug'=>'test']);
    //    //dd($seller);
    //
    //    //$this->signIn();
    //    $boxFromSeller = create('App\Box',['seller_id'=>$seller->id]);
    //    $boxNotFromSeller = create('App\Box');
    //
    //    $this->get('/boxes/'.$seller->slug)
    //         ->assertSee($boxFromSeller->title)
    //         ->assertDontSee($boxNotFromSeller->title);
    //}


}
