<?php

namespace Tests\Feature;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Redis;
use Tests\TestCase;

class RedisTest extends TestCase
{
    use RefreshDatabase;
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        Redis::del('viewed_boxes');
    }
    
    
    /** @test */
    public function it_increments_score_when_a_box_is_viewed()
    {
        $this->assertEmpty(Redis::zrevrange('viewed_boxes', 0, -1));
        $box = create('App\Box');
        $this->call('GET', $box->path());
        $this->assertCount(1, Redis::zrevrange('viewed_boxes', 0, -1));
    }
}
