<?php

namespace Tests\Feature;

use App\ViewedBoxes;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Redis;
use Tests\TestCase;

class RedisTest extends TestCase
{
    use RefreshDatabase;
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->viewed = new ViewedBoxes;
        $this->viewed->reset();
    }
    
    /** @test */
    public function it_increments_score_when_a_box_is_viewed()
    {
        $this->assertEmpty($this->viewed->get());
        $box = create('App\Box');
        $this->call('GET', $box->path());
        $this->assertCount(1, $viewed = $this->viewed->get());
        $this->assertEquals($viewed[0]->title, $box->title);
    }
}
