<?php

namespace App;

use App\Events\ShortStock;
use App\Notifications\OutOfStock;
use Illuminate\Database\Eloquent\Model;

class Inventory extends Model
{
    //
    protected $guarded = [];
    
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        //
        static::created(function ($inventory){
            //return $model;
            //$condition = false;
            //dd($model->inventories);
            if (! $inventory->isOutOfStock() && auth()->check()){
                $item = Item::whereId($inventory->item_id)->first();
                $quantity = $inventory->quantity;
                //event(new ShortStock($item, $quantity));
                auth()->user()->notify(new OutOfStock($item,$quantity));
            }
        });
    }
    
    public function items()
    {
        return $this->hasMany(Item::class);
    }
    
    public function isOutOfStock()
    {
        if ( $this->minimum_stock_quantity == null) return false;
        return $this->minimum_stock_quantity > $this->fresh()->quantity;
    }
    
    public function setMSQ($value)
    {
        $this->minimum_stock_quantity = $value;
    }
   
    // event(new ShortStock($item, $quantity)) 사용시 필요
    //public function notify($item, $quantity)
    //{
    //    auth()->user()->notify(new OutOfStock($item,$quantity));
    //}
    
}

