<?php

namespace App;

use App\Notifications\OutOfStock;
use Illuminate\Database\Eloquent\Model;

class Inventory extends Model
{
    //
    protected $guarded = [];
    
    //////protected static function boot()
    ////{
    //    parent::boot(); // TODO: Change the autogenerated stub
        
        //static::created(function ($model){
        //    return $model;
        //    //$condition = false;
        //    //dd($model->inventories);
        //    //if (!$condition){
        //    //    auth()->user()->notify(new OutOfStock($model));
        //    //}
        //});
    //}
    
    public function items()
    {
        return $this->hasMany(Item::class);
    }
}
