<?php

namespace Tests\Unit;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class NotificationTest extends TestCase
{
    use RefreshDatabase;
    
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->signIn();
    }
    
    /** @test */
    public function it_knows_minimum_stock_quantity()
    {
        $item = create('App\Item');
        
        $item->inventories()->update(['minimum_stock_quantity' => 100]);
        
        $inventory = $item->inventories->first();
        $this->assertEquals(100, $inventory->minimum_stock_quantity);
    }
    
    /** @test */
    public function it_check_current_stock_quantity_when_a_item_is_created()
    {
        
        $item = create('App\Item', ['quantity' => 49]);
        
        $item->inventories()->update(['minimum_stock_quantity' => 50]);
        $this->assertTrue($item->isOutOfStock($item));
        
        $item2 = create('App\Item', ['quantity' => 2]);
        $this->assertFalse($item->IsOutOfStock($item2));
        
    }
    
    /** @test */
    public function it_can_notify_user()
    {
        create('App\Item');
        dd(auth()->user()->notifications);
        //auth()->user()->notify(new OutOfStock($item));
        $this->assertCount(1, auth()->user()->notifications);
    }
    
    /** @test */
    public function it_notifies_user_when_item_is_less_than_minmum_stock_quantity()
    {
        $item = create('App\Item', ['barcode' => 1234, 'quantity' => 50]);
        
        $item->inventories()->update(['minimum_stock_quantity' => 100]);
        //dd($item->inventories);
        $item2 = create('App\Item', ['barcode' => 1234, 'quantity' => 10]);
        
        //dd($item2->quantity);
        
        $this->assertCount(1, auth()->user()->notifications);
        
        //$this->assertTrue($item->isOutOfStock($item));
    }
}
