<?php

namespace Tests\Unit;

use App\Inventory;
use App\Notifications\OutOfStock;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Notifications\DatabaseNotification;
use Tests\TestCase;

class NotificationTest extends TestCase
{
    use RefreshDatabase;
    
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->signIn();
    }
    
    /** @test */
    public function it_knows_minimum_stock_quantity()
    {
        $item = create('App\Item');
        
        $item->inventories()->update(['minimum_stock_quantity' => 100]);
        
        $this->assertEquals(100, $item->inventories()->first()->minimum_stock_quantity);
    }
    
    /** @test */
    public function it_knows_if_an_item_is_out_of_stock()
    {
        $item = create('App\Item',[
            'product_name'=>'곤약젤리','barcode'=>1234, 'quantity'=>10
        ]);
        
        $item->inventories->first()->update(['minimum_stock_quantity'=>100]);
        $this->assertTrue($item->IsOutOfStock($item));
        
        $item->inventories->first()->update(['minimum_stock_quantity'=>5]);
        $this->assertFalse($item->IsOutOfStock($item));
    }
    
    /** @test */
    public function it_can_notify_user()
    {
        create(DatabaseNotification::class);
        //auth()->user()->notify(new OutOfStock($item));
        //auth()->user()->notify(new OutOfStock($item));
        $this->assertCount(1, auth()->user()->notifications);
    }
    
    /** @test */
    public function user_can_clear_notificaitons()
    {
        create(DatabaseNotification::class);
    
        tap(auth()->user(), function($user){
            $notificationId = $user->unreadNotifications->first()->id;
            $this->delete("/profiles/{$user->name}/notifications/{$notificationId}");
            $this->assertCount(0, $user->fresh()->unreadNotifications);
        });
    }
    
    
    
    
    /** @test */
    //public function it_notify_auth_user_when_items_are_less_than_msq()
    //{
    //
    //    $item = create('App\Item', [
    //        'product_name'=> '곤약젤리','barcode' => 1234, 'quantity' => 50
    //    ]);
    //
    //    $this->assertCount(1, auth()->user()->notifications);
    //
    //
    //}
}
